@baseUrl = http://localhost:9191

### GET /api/v1/server-port
GET {{baseUrl}}/api/v1/server-port
Content-Type: application/json

{
    "port": 3001,
    "server_id": "1.1.1.1"
}

### POST /api/v1/server-groups
POST {{baseUrl}}/api/v1/server-groups
Content-Type: application/json

{
    "name": "name from test http curl",
    "desc": "desc from test http curl"
}

### GET /api/v1/server-groups
GET {{baseUrl}}/api/v1/server-groups
Content-Type: application/json

### Get server group by id
GET {{baseUrl}}/api/v1/server-groups/1
Content-Type: application/json

### GET all servers by server group id
GET {{baseUrl}}/api/v1/server-groups/1/servers
Content-Type: application/json

### Add server to server group
POST {{baseUrl}}/api/v1/server-groups/servers
Content-Type: application/json

{
    "name":"fe server for store app",
    "hostname":"fe-store-app-1",
    "ip":"1.2.33.41",
    "group_id":1
}

### Get server by group id and server id
GET {{baseUrl}}/api/v1/server-groups/1/servers/1
Content-Type: application/json

### Generate one time registration token for a new server
GET {{baseUrl}}/api/v1/server/1/regtoken
Content-Type: application/json

### Verify server registration token
POST {{baseUrl}}/api/v1/server/1/verifytoken/e2e402d9e3b9eb240b5d
Content-Type: application/json

{
    "version":"1.0.0",
    "ip":"1.1.1.1",
    "machine_id":"<etc/uuid>"
}

### Get ip address by hostname
POST {{baseUrl}}/api/v1/utils/ip-by-host
Content-Type: application/json

{
    "hostname":"goide.roray.dev"
}