// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repo

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createServerPortStmt, err = db.PrepareContext(ctx, createServerPort); err != nil {
		return nil, fmt.Errorf("error preparing query CreateServerPort: %w", err)
	}
	if q.getServerPortStmt, err = db.PrepareContext(ctx, getServerPort); err != nil {
		return nil, fmt.Errorf("error preparing query GetServerPort: %w", err)
	}
	if q.listServerPortsStmt, err = db.PrepareContext(ctx, listServerPorts); err != nil {
		return nil, fmt.Errorf("error preparing query ListServerPorts: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createServerPortStmt != nil {
		if cerr := q.createServerPortStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createServerPortStmt: %w", cerr)
		}
	}
	if q.getServerPortStmt != nil {
		if cerr := q.getServerPortStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getServerPortStmt: %w", cerr)
		}
	}
	if q.listServerPortsStmt != nil {
		if cerr := q.listServerPortsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listServerPortsStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                   DBTX
	tx                   *sql.Tx
	createServerPortStmt *sql.Stmt
	getServerPortStmt    *sql.Stmt
	listServerPortsStmt  *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                   tx,
		tx:                   tx,
		createServerPortStmt: q.createServerPortStmt,
		getServerPortStmt:    q.getServerPortStmt,
		listServerPortsStmt:  q.listServerPortsStmt,
	}
}
