// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repo

type HttpMonitConfig struct {
	EncodedUrl         string  `json:"encoded_url"`
	Url                string  `json:"url"`
	FriendlyName       string  `json:"friendly_name"`
	Interval           int64   `json:"interval"`
	Retries            int64   `json:"retries"`
	Timeout            int64   `json:"timeout"`
	UpsideDown         bool    `json:"upside_down"`
	MaxRedirects       int64   `json:"max_redirects"`
	Method             string  `json:"method"`
	AcceptedCodes      string  `json:"accepted_codes"`
	BodyEncoding       string  `json:"body_encoding"`
	Body               *string `json:"body"`
	Headers            *string `json:"headers"`
	AuthenticationMode *string `json:"authentication_mode"`
	ExpectedResponse   string  `json:"expected_response"`
}

type HttpMonitDatum struct {
	Url          string  `json:"url"`
	Timestamp    int64   `json:"timestamp"`
	Up           bool    `json:"up"`
	StatusCode   *int64  `json:"status_code"`
	ResponseTime *int64  `json:"response_time"`
	ResponseBody *string `json:"response_body"`
}

type Server struct {
	ID                 string  `json:"id"`
	GroupID            int64   `json:"group_id"`
	Ip                 string  `json:"ip"`
	Mac                *string `json:"mac"`
	RegStatus          string  `json:"reg_status"`
	OneTimeToken       *string `json:"one_time_token"`
	OneTimeTokenExpiry *int64  `json:"one_time_token_expiry"`
	Name               string  `json:"name"`
	Desc               *string `json:"desc"`
	Fqdn               *string `json:"fqdn"`
	AgentVersion       *string `json:"agent_version"`
	Os                 *string `json:"os"`
	Arch               *string `json:"arch"`
	NatsSubject        *string `json:"nats_subject"`
	MonitEnabled       *bool   `json:"monit_enabled"`
	NotifsEnabled      *bool   `json:"notifs_enabled"`
}

type ServerBaseStat struct {
	ServerID     string   `json:"server_id"`
	Timestamp    int64    `json:"timestamp"`
	CpuUsage     *float64 `json:"cpu_usage"`
	MemoryUsage  *float64 `json:"memory_usage"`
	DiskUsage    *float64 `json:"disk_usage"`
	NetworkUsage *float64 `json:"network_usage"`
}

type ServerConfig struct {
	ServerID string `json:"server_id"`
	Key      string `json:"key"`
	Value    string `json:"value"`
}

type ServerGroup struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Desc string `json:"desc"`
}

type ServerPort struct {
	ServerID string `json:"server_id"`
	Port     int64  `json:"port"`
}

type ServerPortsUp struct {
	ServerID  string `json:"server_id"`
	Port      int64  `json:"port"`
	Timestamp int64  `json:"timestamp"`
	Up        bool   `json:"up"`
}

type ServerUp struct {
	ServerID  string `json:"server_id"`
	Timestamp int64  `json:"timestamp"`
	Up        bool   `json:"up"`
	Uptime    *int64 `json:"uptime"`
}
